# Generated by Django 5.0.1 on 2024-04-01 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_timeslot_options_timeslot_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
